# Generated by Django 3.2.13 on 2022-10-15 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20221015_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='calue',
            new_name='value',
        ),
    ]
