# Generated by Django 3.2.13 on 2022-10-16 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchList',
            field=models.ManyToManyField(blank=True, related_name='listings_on_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
